# Generated by Django 4.0.4 on 2022-05-09 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automoviles', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('fecha_inicio_reserva', models.DateField(blank=True, null=True, verbose_name='Inicio Reserva')),
                ('fecha_fin_reserva', models.DateField(blank=True, null=True, verbose_name='Fin Reserva')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('coche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automoviles.coche', verbose_name='Coche')),
                ('usuario', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['fecha_inicio_reserva'],
            },
        ),
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id_cargas', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('coche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automoviles.coche', verbose_name='Coche')),
                ('usuario', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Carga',
                'verbose_name_plural': 'Cargas',
                'ordering': ['id_cargas'],
            },
        ),
    ]
