# Generated by Django 4.0.4 on 2022-04-28 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('automoviles', '0001_initial'),
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='usuario_registro',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.usuario_registrado', verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='carga',
            name='coche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automoviles.coche', verbose_name='Coche'),
        ),
        migrations.AddField(
            model_name='carga',
            name='usuario_concesionario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.usuario_concesionario', verbose_name='Usuario'),
        ),
    ]
