# Generated by Django 4.0.4 on 2022-05-06 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Marca')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['id_marca'],
            },
        ),
        migrations.CreateModel(
            name='TiposCoches',
            fields=[
                ('id_tipo_coche', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('tipo', models.CharField(max_length=25, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipos Coche',
                'verbose_name_plural': 'Tipos Coches',
                'ordering': ['id_tipo_coche'],
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id_modelo', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Modelo')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automoviles.marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'ordering': ['id_modelo'],
            },
        ),
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('matricula', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True, verbose_name='MATRICULA')),
                ('precio_original', models.DecimalField(decimal_places=6, max_digits=13, verbose_name='Precio Original')),
                ('descuento', models.DecimalField(decimal_places=6, max_digits=13, verbose_name='Descuento')),
                ('localizacion', models.CharField(choices=[('01', 'Alaba'), ('02', 'Albacete'), ('03', 'Alicante'), ('04', 'Almeria'), ('05', 'Avila'), ('06', 'Badajoz'), ('07', 'Islas Baleares'), ('08', 'Barcelona'), ('09', 'Burgos'), ('10', 'Caceres'), ('11', 'Cadiz'), ('12', 'Castellon'), ('13', 'Ciudad Real'), ('14', 'Cordoba'), ('15', 'A Coruna'), ('16', 'Cuenca'), ('17', 'Girona'), ('18', 'Granada'), ('19', 'Guadalajara'), ('20', 'Guipuzkoa'), ('21', 'Huelva'), ('22', 'Huesca'), ('23', 'Jaen'), ('24', 'Leon'), ('25', 'Lleida'), ('26', 'La Rioja'), ('27', 'Lugo'), ('28', 'Madrid'), ('29', 'Malaga'), ('30', 'Murcia'), ('31', 'Navarra'), ('32', 'Ourense'), ('33', 'Asturias'), ('34', 'Palencia'), ('35', 'Las Palmas'), ('36', 'Pontevedra'), ('37', 'Salamanca'), ('38', 'Santa Cruz de Tenerife'), ('39', 'Cantabria'), ('40', 'Segovia'), ('41', 'Sevilla'), ('42', 'Soria'), ('43', 'Tarragona'), ('44', 'Teruel'), ('45', 'Toledo'), ('46', 'Valencia'), ('47', 'Valladolid'), ('48', 'Bizkaia'), ('49', 'Zamora'), ('50', 'Zaragoza'), ('51', 'Ceuta'), ('52', 'Melilla')], max_length=2, verbose_name='Localización')),
                ('kilometros', models.FloatField(verbose_name='Kilometros')),
                ('fecha_matriculacion', models.DateField(verbose_name='Fecha Matriculación')),
                ('potencia', models.FloatField(verbose_name='Potencia')),
                ('descripcion', models.CharField(max_length=1024, verbose_name='Descripción')),
                ('garantia', models.CharField(choices=[('0', '2 Meses'), ('1', '4 Meses'), ('2', '6 Meses'), ('3', '8 Meses'), ('4', '10 Meses'), ('5', '12 Meses'), ('6', '14 Meses'), ('7', '16 Meses'), ('8', '18 Meses'), ('9', '20 Meses'), ('10', '22 Meses'), ('11', '24 Meses'), ('12', '28 Meses'), ('13', '30 Meses')], max_length=2, verbose_name='Garantía')),
                ('puertas', models.CharField(choices=[('2', '2 Puertas'), ('3', '3 Puertas'), ('4', '4 Puertas'), ('5', '5 Puertas')], max_length=1, verbose_name='Puertas')),
                ('cambio', models.CharField(choices=[('0', 'Automático'), ('1', 'Manual'), ('2', 'Pilotado'), ('3', 'Transmisión variable')], max_length=1, verbose_name='Cambio')),
                ('reservado', models.BooleanField(default=False, verbose_name='Reservado')),
                ('vendido', models.BooleanField(default=False, verbose_name='Vendido')),
                ('dado_de_baja', models.BooleanField(blank=True, default=False, verbose_name='Dado de baja')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='coche', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automoviles.modelo', verbose_name='Modelo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automoviles.tiposcoches', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Coche',
                'verbose_name_plural': 'Coches',
                'ordering': ['matricula'],
            },
        ),
    ]
