# Generated by Django 4.0.4 on 2022-04-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concesionario',
            fields=[
                ('id_concesionario', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, verbose_name='Concesionario')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Concesionario',
                'verbose_name_plural': 'Concesionarios',
                'ordering': ['id_concesionario'],
            },
        ),
    ]
